export const MyProjects = [
  {
    id: 1,
    name: "Grocery Shop",
    desc: "A Grocery Shop is an efficient and user-friendly Mern(MongoDB, Express, React, Node.js) e-commerce web application designed to facilitate online grocery shopping for customers while empowering grocery owners This application offers a seamless shopping experience and empowers store owners in various ways such as Product Catalog, Search and Filters, Shopping Cart, Checkout & Payment. ",
    image: "/assets/img/grocery.png",
    gitLink: "https://github.com/noudewato/grocery-shop",
    demoLink: "https://grocery-shop-1qcd.onrender.com",
  },
  {
    id: 2,
    name: "Table Menu",
    desc: "A Table Menu MERN (MongoDB, Express, React, Node.js) app is a modern web application that is designed to streamline and enhance the dining experience in a restaurant or similar establishment. This type of app is typically used to facilitate the interaction between customers and restaurant staff by providing an electronic menu accessible through smartphones, tablets, or other devices.  ",
    image: "/assets/img/tablemenu.png",
    gitLink: "https://github.com/noudewato/qr-menu",
    demoLink: "https://node-po46.onrender.com",
  },
  {
    id: 3,
    name: "Hummos Car Dealer",
    desc: "Hummos Car is a simple website build to provide a basic information about rent or buy cars.  It is built with React.js and Saas. ",
    image: "/assets/img/hummos.png",
    gitLink: "Repository: https://github.com/noudewato/buy-car",
    demoLink: "https://hummos.netlify.app",
  },
  {
    id: 4,
    name: "Achimota Golf Club",
    desc: "I developed the Achimota Golf Club website using WordPress, crafting a visually appealing and user-friendly platform. The site is fully responsive, optimized for performance, and designed to enhance the club’s online presence. With intuitive navigation, rich media integration, and SEO best practices, the website effectively showcases Achimota Golf Club’s facilities, events, and services.",
    image: "/assets/img/ahimotagolfclub.png",
    gitLink: "",
    demoLink: "https://achimotagolfclubgh.com/",
  },
  {
    id: 5,
    name: "Agab Construction",
    desc: "Agab Construction Platform is a MERN stack-based real estate and construction website. The user-side (agabconstruction.com) allows visitors to explore land, houses for rent or sale, and construction equipment for purchase or lease. The admin panel (agabconstructionadmin.netlify.app) enables efficient management of listings, projects, and business operations. Built with MongoDB, Express.js, React.js, and Node.js, this platform ensures a seamless experience for users while optimizing real estate and construction services.",
    image: "/assets/img/agab.png",
    gitLink: "",
    demoLink: "https://agabconstruction.com/",
  },
  {
    id: 6,
    name: "IPSL Ghana Limited",
    desc: "I designed and built the IPSL Ghana Limited website using WordPress, creating a seamless and professional online presence. The site features a modern, responsive design, optimized performance, and intuitive navigation, ensuring an excellent user experience. By implementing best SEO practices and custom functionalities, I delivered a platform that effectively represents IPSL Ghana Limited’s brand and services.",
    image: "/assets/img/ipsl.png",
    gitLink: "",
    demoLink: "https://i-psl.com/",
  },
  {
    id: 7,
    name: "Sales Solution System",
    desc: "I designed and built the IPSL Ghana Limited website using WordPress, creating a seamless and professional online presence. The site features a modern, responsive design, optimized performance, and intuitive navigation, ensuring an excellent user experience. By implementing best SEO practices and custom functionalities, I delivered a platform that effectively represents IPSL Ghana Limited’s brand and services.",
    image: "/assets/img/salessolution.png",
    gitLink: "",
    demoLink: "",
  },
  {
    id: 8,
    name: "Brightgate Technologies",
    desc: "Brightgate Technologies Tech Lead is a company specializing in software design, web development, CCTV installation, and data analytics. They provide innovative technology solutions tailored to businesses and individuals, ensuring high-quality software and web applications, robust security systems, and advanced data-driven insights. Their expertise spans across custom software development, website design, surveillance solutions, and big data analytics, helping clients optimize operations and enhance digital security.",
    image: "/assets/img/xsoft.png",
    gitLink: "",
    demoLink: "https://brightgatetechnologies.com/",
  },
  {
    id: 9,
    name: "Restaurant Sales System",
    desc: "Developed with React TypeScript frontend and .NET backend with SQL Server. The system includes features like table reservations, order management, billing, and real-time updates for a seamless dining experience. With a responsive UI, optimized performance, and secure data handling, this solution enhances efficiency for restaurant operations.",
    image: "/assets/img/restaurant.png",
    gitLink: "",
    demoLink: "",
  },
  {
    id: 10,
    name: "Maman E-commerce",
    desc: "Maman E-commerce is a powerful MERN (MongoDB, Express.js, React.js, and Node.js) Stack-based e-commerce solution designed to streamline online shopping experiences. Key features include Product Management, Order Processing, Secure Billing & Payments, Responsive Design, Real-Time Updates, and Scalability. It provides a seamless, user-friendly shopping experience for both customers and store owners.",
    image: "/assets/img/maman.png",
    gitLink: "",
    demoLink: "",
  },
  {
    id: 10,
    name: "Yahweh Property Management",
    desc: "",
    image: "/assets/img/yahweh.png",
    gitLink: "",
    demoLink: "https://yahwehpropertymanagement.com/",
  }
];
